### PR TITLE
Fixes for Xcode 12.5 beta

### PR DESCRIPTION
**Pull request by mmllr**
Signed-off-by: Markus Müller <markus.mueller@kf-interactive.com>

### CODE REVIEW

**Comment by philips77** [comment]
Hello,
May I know the reason for creating `CBMPeer` and `CBMAttribute` classes with `fatalError()`?

**Comment by mmllr** [comment]
Hi, Xcode 12.5 beta complains about an unavailable -init() for these classes (subclassing them is forbidden anyway).

```objc
CB_EXTERN_CLASS @interface CBPeer : NSObject <NSCopying>

- (instancetype)init NS_UNAVAILABLE;
...
CB_EXTERN_CLASS @interface CBAttribute : NSObject

- (instancetype)init NS_UNAVAILABLE;
```
My PR is just a quick fix for getting compiling again. All the CBM classes which use CBMAttribute and CBMPeer overwrite the fatalError implementations.

**Comment by draskovits** [comment]
Xcode 12.5 has been released and this issue is still relevant. Are there any plans to release this fix?

**Comment by philips77** [comment]
Oh, sorry, I completely forgot about this issue. Let me look into it now.

**Comment by moweex** [comment]
any updates about this PR?

**Comment by philips77** [comment]
I'll merge and release it asap. Just give me few hours to finish my current tasks.

**Comment by lucasderraugh** [comment]
To be clear, this would completely break the functionality of these classes, no?

**Comment by philips77** [comment]
If you're using `CBMPeripheral` or `CBMCentralManager`, or the original names but as `typealias` nothing should change.
It's only if you were using the `CBPeer` and `CBAttribute` types directly, now they are not compatible with `CBM..` counterparts.

**Comment by mmllr** [comment]
Yep, it should not break existing code.

**Comment by philips77** [comment]
Released as 0.12.1.

**Pull request merged**
